name: Web pages CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        required: true
        default: false
        description: Publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test:ci
      - name: Add 404 page
        run: cp ./dist/menu-chia/index.html ./dist/menu-chia/404.html
      - name: Publish
        if: github.ref == 'refs/heads/main' || github.event.inputs.publish == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/menu-chia
          cname: chia.code-source.tk
